// Từ vựng HSK 1 (bản 2.0, 150 từ) – biên soạn thủ công, nghĩa tiếng Việt + âm Hán Việt + câu ví dụ.
// Danh sách từ đối chiếu với github.com/drkameleon/complete-hsk-vocabulary (MIT); dữ liệu gốc chỉ có tiếng Anh
// và phiên âm "dạng đầu tiên" của nhiều chữ bị sai (vd. 都 → "Dū họ Đỗ") nên không dùng thẳng được.
// Tuple: [hán tự, pinyin, nghĩa Việt, Hán Việt, emoji, câu Hán, pinyin câu, nghĩa câu]
export type Row = [string, string, string, string, string, string, string, string]
export interface Unit { id: string; title: string; icon: string; rows: Row[] }

export const UNITS: Unit[] = [
  { id: 'greet', title: 'Chào hỏi', icon: '👋', rows: [
    ['你好', 'nǐ hǎo', 'xin chào', '', '👋', '你好！我叫小明。', 'Nǐ hǎo! Wǒ jiào Xiǎo Míng.', 'Xin chào! Tôi tên là Tiểu Minh.'],
    ['谢谢', 'xièxie', 'cảm ơn', 'tạ', '🙏', '谢谢你！', 'Xièxie nǐ!', 'Cảm ơn bạn!'],
    ['不客气', 'bú kèqi', 'không có chi', '', '😊', '谢谢你！——不客气。', 'Xièxie nǐ! — Bú kèqi.', 'Cảm ơn bạn! — Không có chi.'],
    ['对不起', 'duìbuqǐ', 'xin lỗi', 'đối bất khởi', '😔', '对不起，我不认识你。', 'Duìbuqǐ, wǒ bú rènshi nǐ.', 'Xin lỗi, tôi không quen bạn.'],
    ['没关系', 'méi guānxi', 'không sao đâu', 'một quan hệ', '🆗', '对不起！——没关系。', 'Duìbuqǐ! — Méi guānxi.', 'Xin lỗi! — Không sao đâu.'],
    ['再见', 'zàijiàn', 'tạm biệt', 'tái kiến', '🫡', '明天再见！', 'Míngtiān zàijiàn!', 'Mai gặp lại nhé!'],
    ['请', 'qǐng', 'xin mời, làm ơn', 'thỉnh', '🙇', '请坐。', 'Qǐng zuò.', 'Mời ngồi.'],
    ['喂', 'wèi', 'alo', '', '📞', '喂，你好！', 'Wèi, nǐ hǎo!', 'Alo, xin chào!'],
  ] },
  { id: 'pron', title: 'Đại từ', icon: '🙋', rows: [
    ['我', 'wǒ', 'tôi', 'ngã', '🙋', '我是学生。', 'Wǒ shì xuésheng.', 'Tôi là học sinh.'],
    ['你', 'nǐ', 'bạn', '', '🫵', '你好吗？', 'Nǐ hǎo ma?', 'Bạn khỏe không?'],
    ['他', 'tā', 'anh ấy', '', '👨', '他是我的朋友。', 'Tā shì wǒ de péngyou.', 'Anh ấy là bạn của tôi.'],
    ['她', 'tā', 'cô ấy', '', '👩', '她是老师。', 'Tā shì lǎoshī.', 'Cô ấy là giáo viên.'],
    ['我们', 'wǒmen', 'chúng tôi, chúng ta', 'ngã môn', '👫', '我们都是学生。', 'Wǒmen dōu shì xuésheng.', 'Chúng tôi đều là học sinh.'],
    ['这', 'zhè', 'này, đây', '', '👇', '这是书。', 'Zhè shì shū.', 'Đây là sách.'],
    ['那', 'nà', 'kia, đó', '', '👉', '那是我的狗。', 'Nà shì wǒ de gǒu.', 'Kia là con chó của tôi.'],
    ['谁', 'shéi', 'ai', 'thùy', '❓', '他是谁？', 'Tā shì shéi?', 'Anh ấy là ai?'],
  ] },
  { id: 'ask', title: 'Đặt câu hỏi', icon: '❓', rows: [
    ['什么', 'shénme', 'cái gì', '', '❓', '这是什么？', 'Zhè shì shénme?', 'Đây là cái gì?'],
    ['哪', 'nǎ', 'nào', '', '🤔', '你是哪国人？', 'Nǐ shì nǎ guó rén?', 'Bạn là người nước nào?'],
    ['几', 'jǐ', 'mấy', 'kỷ', '🔢', '你几岁？', 'Nǐ jǐ suì?', 'Bạn mấy tuổi?'],
    ['多少', 'duōshao', 'bao nhiêu', 'đa thiểu', '💰', '这个多少钱？', 'Zhège duōshao qián?', 'Cái này bao nhiêu tiền?'],
    ['怎么', 'zěnme', 'thế nào, sao', '', '🤷', '这个字怎么读？', 'Zhège zì zěnme dú?', 'Chữ này đọc thế nào?'],
    ['怎么样', 'zěnmeyàng', 'ra sao, thế nào', '', '🙂', '今天天气怎么样？', 'Jīntiān tiānqì zěnmeyàng?', 'Hôm nay thời tiết thế nào?'],
    ['吗', 'ma', '(trợ từ hỏi) không?', '', '❔', '你好吗？', 'Nǐ hǎo ma?', 'Bạn khỏe không?'],
    ['呢', 'ne', 'còn…thì sao?', '', '💭', '我很好，你呢？', 'Wǒ hěn hǎo, nǐ ne?', 'Tôi khỏe, còn bạn thì sao?'],
  ] },
  { id: 'num1', title: 'Số 1–8', icon: '🔢', rows: [
    ['一', 'yī', 'một', 'nhất', '1️⃣', '我有一个朋友。', 'Wǒ yǒu yí ge péngyou.', 'Tôi có một người bạn.'],
    ['二', 'èr', 'hai', 'nhị', '2️⃣', '现在是二月。', 'Xiànzài shì èr yuè.', 'Bây giờ là tháng hai.'],
    ['三', 'sān', 'ba', 'tam', '3️⃣', '我有三个朋友。', 'Wǒ yǒu sān ge péngyou.', 'Tôi có ba người bạn.'],
    ['四', 'sì', 'bốn', 'tứ', '4️⃣', '我四岁。', 'Wǒ sì suì.', 'Tôi bốn tuổi.'],
    ['五', 'wǔ', 'năm', 'ngũ', '5️⃣', '我有五个苹果。', 'Wǒ yǒu wǔ ge píngguǒ.', 'Tôi có năm quả táo.'],
    ['六', 'liù', 'sáu', 'lục', '6️⃣', '现在六点。', 'Xiànzài liù diǎn.', 'Bây giờ là sáu giờ.'],
    ['七', 'qī', 'bảy', 'thất', '7️⃣', '我七点睡觉。', 'Wǒ qī diǎn shuìjiào.', 'Bảy giờ tôi đi ngủ.'],
    ['八', 'bā', 'tám', 'bát', '8️⃣', '他八岁。', 'Tā bā suì.', 'Cậu ấy tám tuổi.'],
  ] },
  { id: 'num2', title: 'Số & lượng từ', icon: '🎂', rows: [
    ['九', 'jiǔ', 'chín', 'cửu', '9️⃣', '我儿子九岁了。', 'Wǒ érzi jiǔ suì le.', 'Con trai tôi chín tuổi rồi.'],
    ['十', 'shí', 'mười', 'thập', '🔟', '这里有十个人。', 'Zhèlǐ yǒu shí ge rén.', 'Ở đây có mười người.'],
    ['零', 'líng', 'không (số 0)', 'linh', '0️⃣', '二零二六年。', 'Èr líng èr liù nián.', 'Năm 2026.'],
    ['岁', 'suì', 'tuổi', 'tuế', '🎂', '你几岁了？', 'Nǐ jǐ suì le?', 'Bạn mấy tuổi rồi?'],
    ['点', 'diǎn', 'giờ (đúng); chấm', 'điểm', '🕐', '现在三点。', 'Xiànzài sān diǎn.', 'Bây giờ là ba giờ.'],
    ['个', 'ge', '(lượng từ chung) cái, người', 'cá', '👤', '我吃一个苹果。', 'Wǒ chī yí ge píngguǒ.', 'Tôi ăn một quả táo.'],
    ['本', 'běn', '(lượng từ) cuốn', 'bản', '📖', '我有三本书。', 'Wǒ yǒu sān běn shū.', 'Tôi có ba cuốn sách.'],
    ['些', 'xiē', 'một vài, một ít', '', '🔸', '我买一些水果。', 'Wǒ mǎi yìxiē shuǐguǒ.', 'Tôi mua một ít trái cây.'],
  ] },
  { id: 'family', title: 'Gia đình', icon: '👨‍👩‍👧', rows: [
    ['妈妈', 'māma', 'mẹ', '', '👩', '妈妈在家。', 'Māma zài jiā.', 'Mẹ ở nhà.'],
    ['爸爸', 'bàba', 'bố', '', '👨', '爸爸很高兴。', 'Bàba hěn gāoxìng.', 'Bố rất vui.'],
    ['儿子', 'érzi', 'con trai', 'nhi tử', '👦', '我有一个儿子。', 'Wǒ yǒu yí ge érzi.', 'Tôi có một con trai.'],
    ['女儿', 'nǚ’ér', 'con gái', 'nữ nhi', '👧', '我女儿五岁。', 'Wǒ nǚ’ér wǔ suì.', 'Con gái tôi năm tuổi.'],
    ['朋友', 'péngyou', 'bạn bè', 'bằng hữu', '🧑‍🤝‍🧑', '我的朋友在北京。', 'Wǒ de péngyou zài Běijīng.', 'Bạn tôi ở Bắc Kinh.'],
    ['人', 'rén', 'người', 'nhân', '🧍', '他是中国人。', 'Tā shì Zhōngguó rén.', 'Anh ấy là người Trung Quốc.'],
    ['名字', 'míngzi', 'tên', 'danh tự', '📛', '你叫什么名字？', 'Nǐ jiào shénme míngzi?', 'Bạn tên là gì?'],
    ['叫', 'jiào', 'gọi; tên là', 'khiếu', '📣', '我叫小明。', 'Wǒ jiào Xiǎo Míng.', 'Tôi tên là Tiểu Minh.'],
  ] },
  { id: 'school', title: 'Trường học', icon: '🏫', rows: [
    ['老师', 'lǎoshī', 'giáo viên', 'lão sư', '🧑‍🏫', '老师好！', 'Lǎoshī hǎo!', 'Chào thầy/cô ạ!'],
    ['学生', 'xuésheng', 'học sinh', 'học sinh', '🧑‍🎓', '我女儿是学生。', 'Wǒ nǚ’ér shì xuésheng.', 'Con gái tôi là học sinh.'],
    ['同学', 'tóngxué', 'bạn học', 'đồng học', '🧒', '他是我的同学。', 'Tā shì wǒ de tóngxué.', 'Cậu ấy là bạn học của tôi.'],
    ['学校', 'xuéxiào', 'trường học', 'học hiệu', '🏫', '我在学校。', 'Wǒ zài xuéxiào.', 'Tôi đang ở trường.'],
    ['学习', 'xuéxí', 'học, học tập', 'học tập', '📚', '我学习汉语。', 'Wǒ xuéxí Hànyǔ.', 'Tôi học tiếng Trung.'],
    ['字', 'zì', 'chữ', 'tự', '🔤', '这个字怎么写？', 'Zhège zì zěnme xiě?', 'Chữ này viết thế nào?'],
    ['书', 'shū', 'sách', 'thư', '📖', '我喜欢看书。', 'Wǒ xǐhuan kàn shū.', 'Tôi thích đọc sách.'],
    ['汉语', 'Hànyǔ', 'tiếng Hán, tiếng Trung', 'Hán ngữ', '🇨🇳', '我会说汉语。', 'Wǒ huì shuō Hànyǔ.', 'Tôi biết nói tiếng Trung.'],
  ] },
  { id: 'places', title: 'Nơi chốn', icon: '🏥', rows: [
    ['先生', 'xiānsheng', 'ông, ngài; chồng', 'tiên sinh', '🤵', '王先生是医生。', 'Wáng xiānsheng shì yīshēng.', 'Ông Vương là bác sĩ.'],
    ['小姐', 'xiǎojiě', 'cô, tiểu thư', 'tiểu thư', '👩‍💼', '李小姐在家。', 'Lǐ xiǎojiě zài jiā.', 'Cô Lý đang ở nhà.'],
    ['医生', 'yīshēng', 'bác sĩ', 'y sinh', '🧑‍⚕️', '我爸爸是医生。', 'Wǒ bàba shì yīshēng.', 'Bố tôi là bác sĩ.'],
    ['医院', 'yīyuàn', 'bệnh viện', 'y viện', '🏥', '他在医院工作。', 'Tā zài yīyuàn gōngzuò.', 'Anh ấy làm việc ở bệnh viện.'],
    ['商店', 'shāngdiàn', 'cửa hàng', 'thương điếm', '🏪', '我去商店买水果。', 'Wǒ qù shāngdiàn mǎi shuǐguǒ.', 'Tôi đến cửa hàng mua trái cây.'],
    ['饭馆', 'fànguǎn', 'nhà hàng, quán ăn', 'phạn quán', '🍽️', '我们在饭馆吃菜。', 'Wǒmen zài fànguǎn chī cài.', 'Chúng tôi ăn ở nhà hàng.'],
    ['火车站', 'huǒchēzhàn', 'ga tàu hỏa', 'hỏa xa trạm', '🚉', '火车站在前面。', 'Huǒchēzhàn zài qiánmiàn.', 'Ga tàu ở phía trước.'],
    ['家', 'jiā', 'nhà, gia đình', 'gia', '🏠', '我家在北京。', 'Wǒ jiā zài Běijīng.', 'Nhà tôi ở Bắc Kinh.'],
  ] },
  { id: 'time1', title: 'Ngày tháng', icon: '📅', rows: [
    ['今天', 'jīntiān', 'hôm nay', 'kim thiên', '📅', '今天很热。', 'Jīntiān hěn rè.', 'Hôm nay rất nóng.'],
    ['明天', 'míngtiān', 'ngày mai', 'minh thiên', '➡️', '明天我去学校。', 'Míngtiān wǒ qù xuéxiào.', 'Ngày mai tôi đến trường.'],
    ['昨天', 'zuótiān', 'hôm qua', 'tạc thiên', '⬅️', '昨天我很高兴。', 'Zuótiān wǒ hěn gāoxìng.', 'Hôm qua tôi rất vui.'],
    ['现在', 'xiànzài', 'bây giờ', 'hiện tại', '⏰', '现在几点？', 'Xiànzài jǐ diǎn?', 'Bây giờ mấy giờ?'],
    ['时候', 'shíhou', 'lúc, khi', 'thời hậu', '🕰️', '你什么时候去？', 'Nǐ shénme shíhou qù?', 'Khi nào bạn đi?'],
    ['年', 'nián', 'năm', 'niên', '📆', '我在北京住了一年。', 'Wǒ zài Běijīng zhùle yì nián.', 'Tôi sống ở Bắc Kinh một năm.'],
    ['月', 'yuè', 'tháng; mặt trăng', 'nguyệt', '🌙', '现在是五月。', 'Xiànzài shì wǔ yuè.', 'Bây giờ là tháng năm.'],
    ['日', 'rì', 'ngày (trong tháng)', 'nhật', '☀️', '今天是五月一日。', 'Jīntiān shì wǔ yuè yī rì.', 'Hôm nay là ngày 1 tháng 5.'],
  ] },
  { id: 'time2', title: 'Giờ & thời tiết', icon: '🌤️', rows: [
    ['星期', 'xīngqī', 'tuần, thứ', 'tinh kỳ', '🗓️', '今天星期三。', 'Jīntiān xīngqīsān.', 'Hôm nay thứ Tư.'],
    ['上午', 'shàngwǔ', 'buổi sáng', 'thượng ngọ', '🌅', '我上午学习汉语。', 'Wǒ shàngwǔ xuéxí Hànyǔ.', 'Buổi sáng tôi học tiếng Trung.'],
    ['中午', 'zhōngwǔ', 'buổi trưa', 'trung ngọ', '🌞', '中午我吃米饭。', 'Zhōngwǔ wǒ chī mǐfàn.', 'Buổi trưa tôi ăn cơm.'],
    ['下午', 'xiàwǔ', 'buổi chiều', 'hạ ngọ', '🌇', '下午我们去商店。', 'Xiàwǔ wǒmen qù shāngdiàn.', 'Buổi chiều chúng tôi đến cửa hàng.'],
    ['分钟', 'fēnzhōng', 'phút', 'phân chung', '⏱️', '他学习十分钟。', 'Tā xuéxí shí fēnzhōng.', 'Cậu ấy học mười phút.'],
    ['天气', 'tiānqì', 'thời tiết', 'thiên khí', '🌤️', '今天天气很好。', 'Jīntiān tiānqì hěn hǎo.', 'Hôm nay thời tiết rất đẹp.'],
    ['下雨', 'xià yǔ', 'mưa', 'hạ vũ', '🌧️', '明天下雨。', 'Míngtiān xià yǔ.', 'Ngày mai trời mưa.'],
    ['热', 'rè', 'nóng', 'nhiệt', '🥵', '北京的天气很热。', 'Běijīng de tiānqì hěn rè.', 'Thời tiết Bắc Kinh rất nóng.'],
  ] },
  { id: 'verb1', title: 'Động từ chính', icon: '🏃', rows: [
    ['是', 'shì', 'là', 'thị', '🟰', '他是医生。', 'Tā shì yīshēng.', 'Anh ấy là bác sĩ.'],
    ['有', 'yǒu', 'có', 'hữu', '✋', '我有一个女儿。', 'Wǒ yǒu yí ge nǚ’ér.', 'Tôi có một con gái.'],
    ['在', 'zài', 'ở, đang', 'tại', '📍', '我在医院。', 'Wǒ zài yīyuàn.', 'Tôi đang ở bệnh viện.'],
    ['去', 'qù', 'đi', 'khứ', '🚶', '我们去北京。', 'Wǒmen qù Běijīng.', 'Chúng tôi đi Bắc Kinh.'],
    ['来', 'lái', 'đến', 'lai', '🏃', '请来我家。', 'Qǐng lái wǒ jiā.', 'Mời đến nhà tôi.'],
    ['回', 'huí', 'về', 'hồi', '🔙', '我回家。', 'Wǒ huí jiā.', 'Tôi về nhà.'],
    ['做', 'zuò', 'làm', 'tố', '🛠️', '你做什么工作？', 'Nǐ zuò shénme gōngzuò?', 'Bạn làm nghề gì?'],
    ['工作', 'gōngzuò', 'làm việc; công việc', 'công tác', '💼', '我爸爸在北京工作。', 'Wǒ bàba zài Běijīng gōngzuò.', 'Bố tôi làm việc ở Bắc Kinh.'],
  ] },
  { id: 'verb2', title: 'Nghe nói đọc viết', icon: '👀', rows: [
    ['看', 'kàn', 'nhìn, xem, đọc', 'khán', '👀', '我看电视。', 'Wǒ kàn diànshì.', 'Tôi xem tivi.'],
    ['看见', 'kànjiàn', 'nhìn thấy', '', '👁️', '我看见他了。', 'Wǒ kànjiàn tā le.', 'Tôi thấy anh ấy rồi.'],
    ['听', 'tīng', 'nghe', 'thính', '👂', '我听老师说话。', 'Wǒ tīng lǎoshī shuōhuà.', 'Tôi nghe thầy giáo nói.'],
    ['说话', 'shuōhuà', 'nói chuyện', 'thuyết thoại', '🗣️', '老师在说话。', 'Lǎoshī zài shuōhuà.', 'Thầy giáo đang nói.'],
    ['读', 'dú', 'đọc', 'độc', '📖', '请读这个字。', 'Qǐng dú zhège zì.', 'Hãy đọc chữ này.'],
    ['写', 'xiě', 'viết', 'tả', '✍️', '我会写这个字。', 'Wǒ huì xiě zhège zì.', 'Tôi biết viết chữ này.'],
    ['想', 'xiǎng', 'nghĩ; muốn', 'tưởng', '💭', '我想喝水。', 'Wǒ xiǎng hē shuǐ.', 'Tôi muốn uống nước.'],
    ['认识', 'rènshi', 'quen, biết', 'nhận thức', '🤝', '我认识他。', 'Wǒ rènshi tā.', 'Tôi quen anh ấy.'],
  ] },
  { id: 'food', title: 'Ăn uống', icon: '🍎', rows: [
    ['吃', 'chī', 'ăn', '', '😋', '我想吃苹果。', 'Wǒ xiǎng chī píngguǒ.', 'Tôi muốn ăn táo.'],
    ['喝', 'hē', 'uống', '', '🥤', '你喝茶吗？', 'Nǐ hē chá ma?', 'Bạn uống trà không?'],
    ['水', 'shuǐ', 'nước', 'thủy', '💧', '水很热。', 'Shuǐ hěn rè.', 'Nước rất nóng.'],
    ['茶', 'chá', 'trà', 'trà', '🍵', '他喜欢喝茶。', 'Tā xǐhuan hē chá.', 'Anh ấy thích uống trà.'],
    ['米饭', 'mǐfàn', 'cơm', 'mễ phạn', '🍚', '我中午吃米饭。', 'Wǒ zhōngwǔ chī mǐfàn.', 'Trưa tôi ăn cơm.'],
    ['菜', 'cài', 'món ăn; rau', 'thái', '🥬', '我喜欢吃中国菜。', 'Wǒ xǐhuan chī Zhōngguó cài.', 'Tôi thích ăn món Trung Quốc.'],
    ['苹果', 'píngguǒ', 'quả táo', 'bình quả', '🍎', '苹果很大。', 'Píngguǒ hěn dà.', 'Quả táo rất to.'],
    ['水果', 'shuǐguǒ', 'trái cây', 'thủy quả', '🍓', '我喜欢吃水果。', 'Wǒ xǐhuan chī shuǐguǒ.', 'Tôi thích ăn trái cây.'],
  ] },
  { id: 'shop', title: 'Mua sắm', icon: '🛒', rows: [
    ['买', 'mǎi', 'mua', 'mãi', '🛒', '我想买衣服。', 'Wǒ xiǎng mǎi yīfu.', 'Tôi muốn mua quần áo.'],
    ['钱', 'qián', 'tiền', 'tiền', '💵', '我没有钱。', 'Wǒ méiyǒu qián.', 'Tôi không có tiền.'],
    ['块', 'kuài', 'đồng (tiền Trung Quốc)', 'khối', '🪙', '这个苹果三块钱。', 'Zhège píngguǒ sān kuài qián.', 'Quả táo này ba đồng.'],
    ['东西', 'dōngxi', 'đồ vật', 'đông tây', '📦', '我去买东西。', 'Wǒ qù mǎi dōngxi.', 'Tôi đi mua đồ.'],
    ['衣服', 'yīfu', 'quần áo', 'y phục', '👕', '她的衣服很漂亮。', 'Tā de yīfu hěn piàoliang.', 'Quần áo của cô ấy rất đẹp.'],
    ['杯子', 'bēizi', 'cốc, ly', 'bôi tử', '🥛', '杯子里有水。', 'Bēizi lǐ yǒu shuǐ.', 'Trong cốc có nước.'],
    ['桌子', 'zhuōzi', 'cái bàn', 'trác tử', '', '桌子上有书。', 'Zhuōzi shàng yǒu shū.', 'Trên bàn có sách.'],
    ['椅子', 'yǐzi', 'cái ghế', 'ỷ tử', '🪑', '椅子在桌子前面。', 'Yǐzi zài zhuōzi qiánmiàn.', 'Ghế ở trước bàn.'],
  ] },
  { id: 'dir', title: 'Vị trí', icon: '🧭', rows: [
    ['中国', 'Zhōngguó', 'Trung Quốc', 'Trung Quốc', '🇨🇳', '我想去中国。', 'Wǒ xiǎng qù Zhōngguó.', 'Tôi muốn đi Trung Quốc.'],
    ['北京', 'Běijīng', 'Bắc Kinh', 'Bắc Kinh', '🏯', '北京很大。', 'Běijīng hěn dà.', 'Bắc Kinh rất lớn.'],
    ['里', 'lǐ', 'trong', 'lý', '📥', '书在家里。', 'Shū zài jiā lǐ.', 'Sách ở trong nhà.'],
    ['上', 'shàng', 'trên', 'thượng', '⬆️', '书在桌子上。', 'Shū zài zhuōzi shàng.', 'Sách ở trên bàn.'],
    ['下', 'xià', 'dưới', 'hạ', '⬇️', '猫在椅子下。', 'Māo zài yǐzi xià.', 'Con mèo ở dưới ghế.'],
    ['前面', 'qiánmiàn', 'phía trước', 'tiền diện', '⏫', '学校在前面。', 'Xuéxiào zài qiánmiàn.', 'Trường học ở phía trước.'],
    ['后面', 'hòumiàn', 'phía sau', 'hậu diện', '⏪', '我在你后面。', 'Wǒ zài nǐ hòumiàn.', 'Tôi ở phía sau bạn.'],
    ['住', 'zhù', 'ở, sống', 'trụ', '🛏️', '我住在北京。', 'Wǒ zhù zài Běijīng.', 'Tôi sống ở Bắc Kinh.'],
  ] },
  { id: 'daily', title: 'Đời sống', icon: '📺', rows: [
    ['开', 'kāi', 'mở; lái (xe)', 'khai', '🔓', '他开出租车。', 'Tā kāi chūzūchē.', 'Anh ấy lái taxi.'],
    ['坐', 'zuò', 'ngồi; đi (phương tiện)', 'tọa', '💺', '我坐火车去北京。', 'Wǒ zuò huǒchē qù Běijīng.', 'Tôi đi tàu hỏa đến Bắc Kinh.'],
    ['睡觉', 'shuìjiào', 'ngủ', 'thụy giác', '😴', '我女儿在睡觉。', 'Wǒ nǚ’ér zài shuìjiào.', 'Con gái tôi đang ngủ.'],
    ['打电话', 'dǎ diànhuà', 'gọi điện thoại', '', '📱', '我想打电话。', 'Wǒ xiǎng dǎ diànhuà.', 'Tôi muốn gọi điện thoại.'],
    ['电脑', 'diànnǎo', 'máy tính', 'điện não', '💻', '我在电脑上写字。', 'Wǒ zài diànnǎo shàng xiě zì.', 'Tôi viết chữ trên máy tính.'],
    ['电视', 'diànshì', 'tivi', 'điện thị', '📺', '妈妈在看电视。', 'Māma zài kàn diànshì.', 'Mẹ đang xem tivi.'],
    ['电影', 'diànyǐng', 'phim', 'điện ảnh', '🎬', '我喜欢看电影。', 'Wǒ xǐhuan kàn diànyǐng.', 'Tôi thích xem phim.'],
    ['飞机', 'fēijī', 'máy bay', 'phi cơ', '✈️', '我坐飞机去中国。', 'Wǒ zuò fēijī qù Zhōngguó.', 'Tôi đi máy bay đến Trung Quốc.'],
  ] },
  { id: 'adj', title: 'Tính từ', icon: '🐶', rows: [
    ['出租车', 'chūzūchē', 'taxi', 'xuất tô xa', '🚕', '我坐出租车去医院。', 'Wǒ zuò chūzūchē qù yīyuàn.', 'Tôi đi taxi đến bệnh viện.'],
    ['狗', 'gǒu', 'con chó', 'cẩu', '🐶', '我的狗很大。', 'Wǒ de gǒu hěn dà.', 'Con chó của tôi rất to.'],
    ['猫', 'māo', 'con mèo', 'miêu', '🐱', '我喜欢猫。', 'Wǒ xǐhuan māo.', 'Tôi thích mèo.'],
    ['好', 'hǎo', 'tốt, hay', 'hảo', '👍', '他是好人。', 'Tā shì hǎo rén.', 'Anh ấy là người tốt.'],
    ['大', 'dà', 'to, lớn', 'đại', '🐘', '这个杯子很大。', 'Zhège bēizi hěn dà.', 'Cái cốc này rất to.'],
    ['小', 'xiǎo', 'nhỏ', 'tiểu', '🐭', '我的猫很小。', 'Wǒ de māo hěn xiǎo.', 'Con mèo của tôi rất nhỏ.'],
    ['多', 'duō', 'nhiều', 'đa', '➕', '我有很多朋友。', 'Wǒ yǒu hěn duō péngyou.', 'Tôi có rất nhiều bạn.'],
    ['少', 'shǎo', 'ít', 'thiểu', '➖', '我的钱很少。', 'Wǒ de qián hěn shǎo.', 'Tiền của tôi rất ít.'],
  ] },
  { id: 'feel', title: 'Cảm xúc', icon: '❤️', rows: [
    ['漂亮', 'piàoliang', 'đẹp', '', '🌸', '北京很漂亮。', 'Běijīng hěn piàoliang.', 'Bắc Kinh rất đẹp.'],
    ['高兴', 'gāoxìng', 'vui', 'cao hứng', '😄', '认识你很高兴。', 'Rènshi nǐ hěn gāoxìng.', 'Rất vui được quen bạn.'],
    ['喜欢', 'xǐhuan', 'thích', 'hỷ hoan', '❤️', '我喜欢中国。', 'Wǒ xǐhuan Zhōngguó.', 'Tôi thích Trung Quốc.'],
    ['爱', 'ài', 'yêu', 'ái', '😍', '我爱妈妈。', 'Wǒ ài māma.', 'Con yêu mẹ.'],
    ['能', 'néng', 'có thể', 'năng', '💪', '我能说汉语。', 'Wǒ néng shuō Hànyǔ.', 'Tôi có thể nói tiếng Trung.'],
    ['会', 'huì', 'biết (làm gì); sẽ', 'hội', '🧠', '你会说汉语吗？', 'Nǐ huì shuō Hànyǔ ma?', 'Bạn biết nói tiếng Trung không?'],
    ['冷', 'lěng', 'lạnh', 'lãnh', '🥶', '今天很冷。', 'Jīntiān hěn lěng.', 'Hôm nay rất lạnh.'],
  ] },
  { id: 'gram', title: 'Ngữ pháp cơ bản', icon: '🧩', rows: [
    ['的', 'de', 'của', '', '🔗', '这是我的书。', 'Zhè shì wǒ de shū.', 'Đây là sách của tôi.'],
    ['了', 'le', '(đã, rồi)', '', '✅', '我吃了。', 'Wǒ chī le.', 'Tôi ăn rồi.'],
    ['不', 'bù', 'không', 'bất', '🚫', '我不喝茶。', 'Wǒ bù hē chá.', 'Tôi không uống trà.'],
    ['没', 'méi', 'chưa, không có', 'một', '❌', '我没去学校。', 'Wǒ méi qù xuéxiào.', 'Tôi không đến trường.'],
    ['很', 'hěn', 'rất', '', '⭐', '我女儿很漂亮。', 'Wǒ nǚ’ér hěn piàoliang.', 'Con gái tôi rất xinh.'],
    ['太', 'tài', 'quá', 'thái', '😮', '太好了！', 'Tài hǎo le!', 'Tuyệt quá!'],
    ['都', 'dōu', 'đều', 'đô', '👥', '我们都很好。', 'Wǒmen dōu hěn hǎo.', 'Chúng tôi đều khỏe.'],
    ['和', 'hé', 'và, cùng', 'hòa', '➕', '我和朋友去北京。', 'Wǒ hé péngyou qù Běijīng.', 'Tôi và bạn đi Bắc Kinh.'],
  ] },
]
